Repository djangocon/2022.djangocon.us, pull requests merged in 2022-10, with the labels that each got.

#201 ✏️ Add Mariusz to the panel
  _schedule/talks/2022-10-19-17-10-t0-panel-discussion-the-state-of-django.md
Labels: hacktoberfest

#203 Switch our first two keynotes
  _posts/2022-08-02-ruth-ikegah.md
  _schedule/talks/2022-10-17-09-45-t0-come-on-in-the-waters-fine-making-python.md
  _schedule/talks/2022-10-18-09-45-t0-keynote-women-of-open-source-community-a.md
Labels: hacktoberfest-accepted

#209 Initial bio and image for Timothy Allen.
  _presenters/timothy-allen.md
  _schedule/talks/2022-10-17-15-50-t1-miracles-in-anarchy.md
  _schedule/talks/2022-10-17-15-50-t1-war-stories-scaling-django.md
  static/img/presenters/timothy-allen.jpg
Labels: hacktoberfest-accepted

#212 ✏️ Add code of conduct team to CoC team members
  _organizers/adam-fast.md
  _organizers/carol-ganz.md
  _organizers/catherine-holmes.md
  _organizers/dawn-wages.md
  _organizers/drew-winstel.md
  _organizers/jeff-triplett.md
  _organizers/jorge-gimeno.md
  _organizers/katia-lira.md
  _organizers/lacey-williams-henschel.md
  _organizers/logan-kilpatrick.md
  _organizers/noah-alorwu.md
Labels: hacktoberfest-accepted

#211 📅 Adjust schedule for Tuesday morning
  _schedule/talks/2022-10-18-10-00-t0-opening-remarks.md
  _schedule/talks/2022-10-18-10-10-t0-keynote-women-of-open-source-community-a.md
Labels: hacktoberfest-accepted

#215 📆 Add Wednesday's sponsored talk from STG
  _presenters/david-graves.md
  _presenters/thulasidharan-lg.md
  _schedule/talks/2022-10-19-10-30-t0-sponsored-talk-summit-technology-group.md
  static/img/presenters/david-graves.jpeg
  static/img/presenters/thulasidharan-lg.jpeg
Labels: hacktoberfest-accepted

#220 Add sponsor O'Reilly
  _sponsors/2022-10-12-oreilly.md
  static/img/sponsors/oreilly.png
Labels: hacktoberfest-accepted

#216 Add "Welcome Reception" to the schedule for Monday
  _layouts/session-details.html
  _schedule/talks/2022-10-17-17-40-t0-welcome-reception.md
Labels: hacktoberfest-accepted

#218 Opening Reception at DjangoCon US and board game night
  _posts/2022-10-13-opening-reception.md
Labels: hacktoberfest-accepted

#222 📝 Add childcare link
  _pages/venue.html
Labels: hacktoberfest, hacktoberfest-accepted

#223 📝 Miscellaneous updates
  Gemfile.lock
  _layouts/home.html
  _pages/about.html
  _pages/faqs.html
  _pages/opportunity-grants.md
  _pages/speaking.md
  _pages/sponsors-information.md
  _pages/tickets.html
Labels: hacktoberfest, hacktoberfest-accepted

#227 📝 Update speaker title
  _presenters/heidi-white.md
Labels: hacktoberfest

#244 Comment out buy tickets now button
  _layouts/session-details.html
Labels: hacktoberfest

#245 Add slides
  _layouts/session-details.html
  _schedule/talks/2022-10-17-11-10-t0-the-django-admin-is-your-oyster-lets-its.md
  _schedule/talks/2022-10-17-11-10-t1-django-logging-demystified.md
  _schedule/talks/2022-10-17-16-40-t0-nurturing-a-legacy-codebase.md
  _schedule/talks/2022-10-17-16-40-t1-massively-increase-your-productivity-on.md
  _schedule/talks/2022-10-18-14-50-t1-method-resolution-order-mro-in-python.md
  _schedule/talks/2022-10-18-15-50-t0-just-enough-ops-for-developers.md
  _schedule/talks/2022-10-18-16-40-t0-your-first-deployment-shouldn-t-be-so.md
  _schedule/talks/2022-10-19-14-00-t0-why-large-django-projects-need-a-data.md
  _schedule/talks/2022-10-19-14-50-t0-a-pythonic-full-text-search.md
Labels: hacktoberfest, hacktoberfest-accepted

#243 :pencil: Adds stats and no mac
  _pages/homepage-recap.html
Labels: hacktoberfest, hacktoberfest-accepted

#252 Add contributors
  .all-contributorsrc
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
